### ISSUE TITLE
Send Grid Broken on Dev

### ISSUE THREAD

**Issue by justinmc** [Autodesk/molecular-design-applications#99]
Posted in Slack by @PeterRJones:
```01:25:38.479Z DEBUG mdt:  (f=processJobFinished, runId=S1kM7_Ywe)
  jobResult: {
    "jobId": "S1kM7_Ywe",
    "status": "success",
    "exitCode": 0,
    "stdout": null,
    "stderr": null,
    "resultJson": "https://d3bt947tva2i1l.cloudfront.net/S1kM7_Ywe/result.json",
    "inputsBaseUrl": "https://d3bt947tva2i1l.cloudfront.net/S1kM7_Ywe/inputs/",
    "outputsBaseUrl": "https://d3bt947tva2i1l.cloudfront.net/S1kM7_Ywe/outputs/",
    "inputs": [
      "input.pdb"
    ],
    "outputs": [
      "out.pdb"
    ],
    "error": null,
    "definition": {
      "inputs": [
        "input.pdb"
      ],
      "mountApiServer": false,
      "parameters": {
        "cpus": 1,
        "maxDuration": 120000
      },
      "jobId": "S1kM7_Ywe",
      "image": {
        "value": "docker.io/busybox:latest",
        "type": "image",
        "optionsCreate": {
          "Env": [
            "CCC=ccc.bionano.autodesk.com:9000",
            "INPUTS=/inputs",
            "OUTPUTS=/outputs",
            "OUTPUTS_HOST_MOUNT=outputs__S1kM7_Ywe_1",
            "INPUTS_HOST_MOUNT=inputs__S1kM7_Ywe_1"
          ],
          "Cmd": [
            "cp",
            "/inputs/input.pdb",
            "/outputs/out.pdb"
          ],
          "WorkingDir": "/outputs",
          "HostConfig": {
            "LogConfig": {
              "Type": "json-file",
              "Config": {}
            },
            "Binds": [
              "outputs__S1kM7_Ywe_1:/outputs:rw",
              "inputs__S1kM7_Ywe_1:/inputs:rw"
            ]
          },
          "Image": "docker.io/busybox:latest",
          "Labels": {
            "jobId": "S1kM7_Ywe",
            "computeId": "S1kM7_Ywe_1"
          }
        }
      },
      "appendStdOut": true,
      "appendStdErr": true
    },
    "stats": [
      1485566727492,
      1485566727492,
      1,
      0,
      0,
      0
    ]
  }
{ SendGridError: Response error
    at /app/server/node_modules/sendgrid/lib/sendgrid.js:115:19
    at IncomingMessage.<anonymous> (/app/server/node_modules/sendgrid-rest/lib/client.js:108:9)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  message: 'Response error',
  response: 
   { statusCode: 401,
     body: { errors: [Object] },
     headers: 
      { server: 'nginx',
        date: 'Sat, 28 Jan 2017 01:25:38 GMT',
        'content-type': 'application/json',
        'content-length': '116',
        connection: 'close',
        'x-frame-options': 'DENY' } } }```

**Comment by justinmc** [comment]
Fixed by setting the sendgrid key in Jenkins thanks to @PeterRJones!
